version: 0.2

batch:
  fast-fail: true
  # build-list:
  # build-matrix:
  # build-graph:

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - yarn
  pre_build:
    on-failure: ABORT
    commands:
      - echo VITE_API_URL=$BACKEND_API_URL > .env
      - echo VITE_KEY_API=AIzaSyCswOitF1U7DytAmFm6MYt-EE9DO-cOT2o >> .env
  build:
    on-failure: ABORT
    commands:
      - yarn run build
  post_build:
    on-failure: ABORT
    commands:
      - aws s3 cp dist/ $S3_BUCKET_DESTINATION_URI --recursive
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
