name: Sync to GitHub
on:
  push:
    branches:
      - main
      - ppr
      - prd
      - develop
env:
  MESSAGE:
  TAG:

jobs:
  sync-git:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false
          fetch-depth: 0
    
      - name: Change git repo
        run: |
          sudo apt-get install gawk -y
          MESSAGE=$(awk 'gsub(/Message:/, ""); NR==0' customer_commit.txt)
          TAG=$(awk 'gsub(/Tag:/, ""); NR==0' customer_commit.txt)
          echo "TAG=$TAG" >> $GITHUB_ENV
          rm -rf .git
          git init
          git config user.email "${{ vars.SYNC_MAIL }}"
          git config user.name "${{ vars.SYNC_USER }}"
          git checkout -b devops
          git remote add -f origin https://${{ secrets.SYNC_TOKEN }}@github.com/${{ vars.SYNC_REPO }}
          git fetch
          git checkout -f origin/${{ github.ref_name }} || echo "No branch"
          git checkout ${{ github.ref_name }}
          echo "Debug 1"
          rm -rf .github azure-pipelines.yml customer_commit.txt
          git pull origin ${{ github.ref_name }} 
          echo "Debug 2"
          git add .
          git status
          echo $MESSAGE
          git commit -m "${MESSAGE}"\
          git branch -D devops
          git push origin ${{ github.ref_name }} -f

      - name: Push tag
        if: env.TAG != ''
        run: |
          git tag $TAG && git push origin $TAG || echo "tag $TAG already exists"
