name: Sync to GitHub
on:
  push:
    branches:
      - main
      - ppr
      - prd
      - develop
env:
  MESSAGE:
  TAG:

jobs:
  sync-git:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false
          fetch-depth: 0
      - name: Config Git Credential
        run: |
          git config user.email "${{ vars.SYNC_MAIL }}"
          git config user.name "${{ vars.SYNC_USER }}"
      - name: Change git repo
        run: |
          sudo apt-get install gawk -y
          echo $(awk 'gsub(/Message:/, ""); NR==0' customer_commit.txt) = $MESSAGE
          echo $(awk 'gsub(/Tag:/, ""); NR==0' customer_commit.txt) = $TAG
          rm -rf .git
          git init
          git checkout -b ${{ github.ref_name }}
          git remote add origin "${{ vars.CUSTOMER_REPO }}"
          rm -rf .github azure-pipelines.yml customer_commit.txt
          git add .
          git commit -m ${{ MESSAGE }}

      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}
          repository: ${{ vars.SYNC_REPO }}
          branch: ${{ github.ref_name }}

      - name: Push tag
        if: "${{ TAG }}" != ''
        run: |
          git tag ${{ TAG }}
          git push origin ${{ TAG }}
